// Generated by SolidPython 1.1.3 on 2025-06-09 14:13:41


difference() {
	cube(size = [54, 22, 2]);
	translate(v = [15.0000000000, 11.0000000000, -1]) {
		difference() {
			cylinder($fn = 100, d = 12, h = 4);
			translate(v = [-6.0000000000, 5, 0]) {
				cube(size = [12, 12, 4]);
			}
		}
	}
	translate(v = [39.0000000000, 11.0000000000, -1]) {
		mirror(v = [0, 1, 0]) {
			difference() {
				cylinder($fn = 100, d = 12, h = 4);
				translate(v = [-6.0000000000, 5, 0]) {
					cube(size = [12, 12, 4]);
				}
			}
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
# Working on Ubuntu 20.04 (zen) 2025-06-09 jmb
# pip install solidpython
# apt install openscad

# python3 fuse-plate.py && openscad -o fuse-plate.stl fuse-plate.scad

from solid import *
from solid.utils import *

# Dimensions
plate_length = 54
plate_width = 22
plate_thickness = 2
hole_diameter = 12
hole_radius = hole_diameter / 2
flat_offset = 5
hole_spacing = 24

def flat_hole():
    """Create a 12mm round hole with 1mm flat on one side."""
    cyl = cylinder(d=hole_diameter, h=plate_thickness + 2, segments=100)
    flat = cube([hole_diameter, hole_diameter, plate_thickness + 2])
    flat = translate([-hole_radius, flat_offset, 0])(flat)
    return difference()(cyl, flat)

def make_plate():
    # Base plate
    base = cube([plate_length, plate_width, plate_thickness])
    
    # Hole positions
    x1 = plate_length / 2 - hole_spacing / 2
    x2 = plate_length / 2 + hole_spacing / 2
    y = plate_width / 2

    # Holes with flats facing outward along long axis
    # hole1 = translate([x1, y, -1])(flat_hole())
    # hole2 = mirror([1, 0, 0])(translate([-x2, y, -1])(flat_hole()))

    hole1 = translate([x1,  y, -1])(flat_hole())
    #hole2 = mirror([0, 1, 0])(flat_hole())
    hole2 = translate([x2,  y, -1])(
            mirror([0, 1, 0])(flat_hole()))

    return difference()(base, hole1, hole2)

scad_render_to_file(make_plate(), 'fuse-plate.scad')
 
 
************************************************/
